### ISSUE TITLE
Plan to refactor peerpad to use peer-crdt.

### ISSUE THREAD

**Issue by fritzy** [ipfs-shipyard/peer-star#7]
Starting a goal of a new peerpad by mid-June, using peer-crdt. There are some challenges.

https://github.com/ipfs/dynamic-data-and-capabilities/issues?q=is%3Aissue+is%3Aopen+label%3ACRDT

The challenges are:

## peer-crdt performance

There's been some work on specific bugfixes for performance, but going forward, here is how we're tackling optimizations:
https://github.com/ipfs-shipyard/peer-crdt/issues/7

## Identity

There's been a lot discussion and research on identity. This is the approach we're going to take on it in the short term.
https://github.com/ipfs-shipyard/peer-star/issues/3#issuecomment-387661407

### Past discussion and research
- https://github.com/ipfs/dynamic-data-and-capabilities/issues/7  (of particular note https://hackmd.io/s/H17TwVqsz#)
- https://github.com/ipfs/dynamic-data-and-capabilities/issues/12
https://github.com/ipfs/dynamic-data-and-capabilities/issues/15

### Current Development

- https://github.com/ipfs-shipyard/dapp-identity-api (needs to be converted to use DID format and verbs as of this writing)
- [x] DID client for generating key-pairs, DIDs, and interacting with the service (if available) or working without, if offline.

## ACL

ACL relies on getting identity right, and then have a main admin give permissions for other users or sessions to perform actions.

### Disccusions

https://github.com/ipfs-shipyard/peer-star/issues/6

## RichText Type

Due to the ACL discussion, we may want to have a richtext variation with embedded ACL as well.

## Rewriting/Refactoring peerpad-core

Once we have all of the pieces in place, it'll be time to start rebuilding peerpad-core. We can do this before all of the necessary optimizations are in place, and it'll simply improve with time.

## Design

Design efforts have been underway to improve branding and UX.

## Hardening

The idea is to have a new peerpad ready for the big conference this summer, so we'll want to start using it and abusing it in earnest once the first version is deployed. We should have time to make a very solid product!

**Comment by one000mph** [comment]
@fritzy sounds like DID and several other efforts mentioned here have been solved. Can you provide an update on this effort on monday?

**Comment by fritzy** [comment]
Identity management is done, although we need to finish the identity service. Eventually everything can be moved to the identity RFC using what we've done as the basis. https://github.com/ipfs-shipyard/peer-star/blob/rfc-identity/docs/rfc-identity.md

Permissions will be implemented using the current encryption key url sharing, since the document needs to be encrypted anyway.

Performance is much better than it used to be, although it is still an issue for peer-crdt. There are more optimizations in the works, but it is unclear how performant it will be by the end of July.

A new textarea binding is in the works for peer-crdt, and we should be finishing that in the next day or two, at which point we'll start rewriting peer-pad-core with these new components.

**Comment by one000mph** [comment]
@diasdavid here is the update about the status of the peer-pad refactor

**Comment by bolaa100** [comment]
# resul togel china

resul togel china - Selamat malam,pagi,siang dan sore togel china adalah permainan judi yang terbanyak di meminati orang. dapat ditunjukkan banyaknya, beberapah pemain togel china yang membuat jumlah pemain melalui type judi lainnya.

kenapa beberapa orang mengandrungi togel china?, karena mudah cukup hanya memasang nomor, bila nomor yang kita pasang sudah keluar karena itu kita akan mendapat keuntungan.

indonesia banyak penggemar judi type ini, karenanya kami betul-betul merecomendasikan jika kalian penggemar judi togel type ini.

## data togel china pragmatic slots
Bermain togel di pragmatic slot memiliki keuntungan lebih gacor, lebih terpercaya dan sudah di meminati beberapa ribu orang, dan sudah banyak yang bergabung jadi member.

Togel china di pragmatic slot mudah di akses tidak ribet, banyak potongan promo dan harga.

Bila Anda bertanya, mengapa ada anggota yang bisa memperoleh keuntungan sampai juta-an rupiah dalam penghitungan hari, karenanya jawabannya sederhana, di pragmatic slot

Beberapa anggota bisa memperoleh dana tercepat karena keuntungan yang didapat tidak cuma dari permainan judi saja, tapi dari bermacam bonus yang tersedia.

Sekarang ini, bila anda ingin bermain judi tak perlu secara darat tetapi secara onilne sudah bisa. Karena ada nama agen pragmatic slot.

yang disebut situs togel China yang telah berdiri dari tahun 2019 lalu, dan sebuah organisasi yang terspesialisasi pada bagian perjudian tebak angka.

karenanya anda bisa untuk jadi pangkalan untuk memasang angka toto yang paling nyaman.

## angka keluaran china
setiap orang yang memperdalam perjudian togel pasti betul-betul lah mengenal dengan angka keluaran china panggilan ini adalah panggilan untuk mendeskripsikan atau yang dimaksud adalah keluaran angka togel.

dan ada beberapa kata majas yang sebenarnya arti dan maksudnya sama

dari semua orang yang turuti perjudian togel china kalimat berikut yang di nantikan oleh semua pemain, apa angka yang mereka pasang sudah keluar.

## pasaran togel china
setiap pemain memiliki kekhasan dalam menebak angka keluaran togel, biasanya mereka memiliki teknik sendiri-sendiri.

yang artinya setiap teknik yang di punya pemain berbeda beda.

tapi berikut uniknya beberapa pemain biasanya teknik yang mereka gunakan secara rumus.

rumus apa yang mereka gunakan? heemm jangan skip atau terlewatkan artikel ini karena ada beberapa pengetahuan yang ingin saya untuk ke anda.

## togel china hari ini
untuk pengeluaran togel pada agen kami siapkan judi type ini, tentu siapkan live togel keluaran terbaru dari pasaran togel china.

kami memiliki banyak agen yang bisa kalian akses kapan pun yang kalian ingin, konsumen service kami online 24jam.

## PARTNER PRAGMATIC SLOT
Bola100 adalah partner kami sejak berdirinya pragmatic slot bola100, dan memiliki banyak permainan.

tentu saja bukan hanya togel saja tapi banyak permainan judi lainnya diantaranya.

- Pragmatic play
- Spade gaming
- Poker
- live22
- slot88

## berbagai macam cara system deposit
Mekanisme deposit kami memiliki cara yang memudahkan untuk beberapa anggotanya kalian bisa mudah deposit dengan kedahsyatan teknologi sekarang ini seperti dompet digital salah satunya.

## deposit via pulsa
pulsa adalah kalimat yang kenal dalam telinga kita, perlu anda ketahui bila kami terima [deposit via pulsa](http://5.188.34.46/slot-depo-pulsa-tanpa-potongan/) untuk semuanya anggota sampai betul-betul memudahkan beberapa anggota.

## deposit via dana
dompet digital dana benar-benar sangat populer di mata masyarakat maka dari itu kami terima dan siapkan

[deposit via dana](http://5.188.34.46/slot-minimal-deposit-10-ribu-via-dana/) agar kalian yang menggunakan dompet digital dana dapat deposit secara mudah.

## deposit via shopeepay
shopeepay adalah dompet punyai toko online paling penting di indonesia yaitu shopee.

tetapi banyak pengguna shopeepay tidak cuma untuk berbelanja di toko online shopee saja.

tapi bisa untuk transaksi lain di luar dari toko online shopee itu, dengan demikian kami siapkan [deposit via shopeepay](http://5.188.34.46/deposit-via-shopeepay/) agar anggota yang memiliki dompet shopeepay.

dapat bermain dan tidak memiliki permasalahan atas proses transaksi bisnis bisnis.

## deposit via gopay
gopay adalah dompet digital punyai satu diantaranya perusahaan ojek online, yaitu GOJEK.

tapi gopay tidak cuma untuk trasaksi pada product perusahaan itu saja.

banyak pengguna gopay, menggunakan gopay sebagai transaksi di luar dari perusahaan itu maka dari itu kami terima [deposit via gopay](http://5.188.34.46/judi-slot-online-deposit-via-gopay/).

## deposit via ovo
ovo ialah salah satunya perusahaan dompet digital yang bergerak dalam indonesia, ia pernah populer pada tahun 2021 lalu, lebih kurang sama dengan dompet digital DANA, tapi memiliki ketidaksesuaian yang jelas untuk beberapa ciri has mereka masing-masing.

tapi kami tidak tutup mata karenanya kami persiapkan , dan terima [deposit via ovo](http://5.188.34.46/slot-deposit-ovo-10rb/) agar yang menggunakan ovo bisa juga deposit dengan gampang

Kalian tidak perlu ketidaktahuan jika betul ada permasalahan atau tidak memiliki debet atau malas karena ribet

dengan ATM kalian, bisa menggunakan alternatif lain yaitu dengan dompet digital.
